export interface Product {
  id: string;
  name: string;
  category: "Laptops" | "Components" | "Audio" | "Gaming" | "Mobile" | "Accessories";
  price: number; // In PHP (₱)
  originalPrice?: number;
  condition: "New" | "Like New" | "Good" | "Fair";
  rating: number;
  reviewCount: number;
  sellerName: string;
  isVerifiedSeller: boolean;
  location: string;
  isFeatured?: boolean;
  section: "Recommended for you" | "Pre-owned finds" | "Popular in gaming" | "Trusted sellers";
  specs: string;
  badge?: string;
  gradientFrom: string;
  gradientTo: string;
}

export const CATEGORIES = [
  "All",
  "Laptops",
  "Gaming",
  "Components",
  "Mobile",
  "Audio",
  "Accessories",
] as const;

export type CategoryFilter = (typeof CATEGORIES)[number];

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Asus ROG Strix G16 Gaming Laptop",
    category: "Laptops",
    price: 42500,
    originalPrice: 49990,
    condition: "Like New",
    rating: 4.9,
    reviewCount: 38,
    sellerName: "TechVault Cebu",
    isVerifiedSeller: true,
    location: "Cebu City, Central Visayas",
    isFeatured: true,
    section: "Recommended for you",
    specs: "Intel i7-13650HX, RTX 4060 8GB, 16GB DDR5, 512GB NVMe SSD, 165Hz FHD+ Display",
    badge: "Featured Deal",
    gradientFrom: "#432c45",
    gradientTo: "#281729",
  },
  {
    id: "prod-2",
    name: "NVIDIA GeForce RTX 4070 Dual Fan OC 12GB",
    category: "Components",
    price: 18900,
    originalPrice: 22500,
    condition: "Good",
    rating: 4.8,
    reviewCount: 24,
    sellerName: "Cebu GPU Corner",
    isVerifiedSeller: true,
    location: "Mandaue City, Cebu",
    section: "Popular in gaming",
    specs: "12GB GDDR6X, DLSS 3, Ray Tracing Gen 3, PCIe 4.0, Dual Ball Bearing Fans",
    gradientFrom: "#684d72",
    gradientTo: "#4a3054",
  },
  {
    id: "prod-3",
    name: "Keychron Q1 Pro Wireless Mechanical Keyboard",
    category: "Accessories",
    price: 3250,
    originalPrice: 3990,
    condition: "Like New",
    rating: 4.9,
    reviewCount: 42,
    sellerName: "Keycraft PH",
    isVerifiedSeller: true,
    location: "Lapu-Lapu City, Cebu",
    section: "Pre-owned finds",
    specs: "CNC Aluminum Body, Gateron Jupiter Red Switches, QMK/VIA Support, Bluetooth 5.1",
    gradientFrom: "#a37282",
    gradientTo: "#7d4e5d",
  },
  {
    id: "prod-4",
    name: "Samsung Galaxy S23 Ultra 256GB Phantom Black",
    category: "Mobile",
    price: 24990,
    originalPrice: 31500,
    condition: "Like New",
    rating: 4.9,
    reviewCount: 56,
    sellerName: "Visayas Mobile Hub",
    isVerifiedSeller: true,
    location: "Cebu City, Central Visayas",
    section: "Recommended for you",
    specs: "Snapdragon 8 Gen 2, 200MP Camera, S-Pen Built-in, 5000mAh Battery, 120Hz AMOLED",
    gradientFrom: "#544061",
    gradientTo: "#34243b",
  },
  {
    id: "prod-5",
    name: "Sony PlayStation DualSense Wireless Controller",
    category: "Gaming",
    price: 3490,
    originalPrice: 3990,
    condition: "New",
    rating: 5.0,
    reviewCount: 67,
    sellerName: "PixelPlay Cebu",
    isVerifiedSeller: true,
    location: "Cebu City, Central Visayas",
    section: "Popular in gaming",
    specs: "Haptic Feedback, Adaptive Triggers, Built-in Microphone, Cosmic Red Edition",
    gradientFrom: "#694975",
    gradientTo: "#432c45",
  },
  {
    id: "prod-6",
    name: "LG UltraGear 27\" QHD 165Hz IPS Gaming Monitor",
    category: "Components",
    price: 8750,
    originalPrice: 11200,
    condition: "Good",
    rating: 4.7,
    reviewCount: 19,
    sellerName: "DisplayTech Cebu",
    isVerifiedSeller: true,
    location: "Talisay City, Cebu",
    section: "Trusted sellers",
    specs: "2560x1440 QHD IPS, 1ms GtG Response, G-Sync Compatible, HDR10",
    gradientFrom: "#3a233e",
    gradientTo: "#201524",
  },
  {
    id: "prod-7",
    name: "Samsung 980 PRO 1TB PCIe 4.0 NVMe M.2 SSD",
    category: "Components",
    price: 4200,
    originalPrice: 5400,
    condition: "New",
    rating: 4.9,
    reviewCount: 88,
    sellerName: "Silicon Bay Cebu",
    isVerifiedSeller: true,
    location: "Mandaue City, Cebu",
    section: "Trusted sellers",
    specs: "Up to 7,000 MB/s Read Speed, In-House Controller, Thermal Control Solution",
    gradientFrom: "#684e70",
    gradientTo: "#442f4b",
  },
  {
    id: "prod-8",
    name: "Sony WH-1000XM5 Wireless ANC Headphones",
    category: "Audio",
    price: 5990,
    originalPrice: 7990,
    condition: "Fair",
    rating: 4.8,
    reviewCount: 31,
    sellerName: "AudioPhile Cebu",
    isVerifiedSeller: true,
    location: "Cebu City, Central Visayas",
    section: "Pre-owned finds",
    specs: "Active Noise Cancellation, Auto NC Optimizer, 30-hr Battery, Multi-point Connect",
    gradientFrom: "#7d6484",
    gradientTo: "#544061",
  },
  {
    id: "prod-9",
    name: "Logitech G Pro X Superlight Wireless Mouse",
    category: "Gaming",
    price: 4850,
    originalPrice: 6200,
    condition: "Like New",
    rating: 4.9,
    reviewCount: 51,
    sellerName: "PixelPlay Cebu",
    isVerifiedSeller: true,
    location: "Cebu City, Central Visayas",
    section: "Popular in gaming",
    specs: "HERO 25K Sensor, Under 63g Ultra-Lightweight, Lightspeed Wireless, Zero-Additive PTFE",
    gradientFrom: "#a37282",
    gradientTo: "#684d72",
  },
  {
    id: "prod-10",
    name: "Anker 737 Power Bank 24,000mAh 140W",
    category: "Accessories",
    price: 4600,
    originalPrice: 5800,
    condition: "New",
    rating: 5.0,
    reviewCount: 43,
    sellerName: "PowerUp Cebu",
    isVerifiedSeller: true,
    location: "Mandaue City, Cebu",
    section: "Trusted sellers",
    specs: "140W Two-Way Fast Charging, Smart Digital Display, PowerIQ 4.0, ActiveShield 2.0",
    gradientFrom: "#48334c",
    gradientTo: "#281729",
  },
  {
    id: "prod-11",
    name: "SteelSeries Arctis Nova 7 Wireless Headset",
    category: "Audio",
    price: 6800,
    originalPrice: 8500,
    condition: "Good",
    rating: 4.7,
    reviewCount: 22,
    sellerName: "AudioPhile Cebu",
    isVerifiedSeller: true,
    location: "Cebu City, Central Visayas",
    section: "Pre-owned finds",
    specs: "Simultaneous Wireless 2.4GHz & Bluetooth, 38-hour Battery, Sonar Audio Software",
    gradientFrom: "#694975",
    gradientTo: "#352238",
  },
  {
    id: "prod-12",
    name: "MacBook Air M2 13.6\" 8GB 256GB Starlight",
    category: "Laptops",
    price: 38900,
    originalPrice: 46990,
    condition: "Like New",
    rating: 4.9,
    reviewCount: 45,
    sellerName: "TechVault Cebu",
    isVerifiedSeller: true,
    location: "Cebu City, Central Visayas",
    section: "Recommended for you",
    specs: "Apple M2 8-core CPU 8-core GPU, 8GB Unified Memory, 256GB SSD, MagSafe 3",
    gradientFrom: "#544061",
    gradientTo: "#201524",
  },
];
